//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftBird.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donator
    {
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Zip { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Catagories { get; set; }
        public string Registry { get; set; }
    }
}
